# -*- coding: utf-8 -*-
# Database
SQL_DRIVER = '{ODBC Driver 13 for SQL Server}'
# SQL_DRIVER = '{SQL Server Native Client 11.0}'
# SQL_TRUSTED = 'yes'

# OData Service
ODATA_TENANT_URL = 'https://my300972-api.s4hana.ondemand.com'
ODATA_USER = 'INTEGRATION'
ODATA_PASSWORD = 'bGJZww]cfz9mFimjjhifvoVKYidmSRdMJFiuYKFk'
ODATA_BASE_URL = ODATA_TENANT_URL + '/sap/opu/odata/sap/'
ODATA_GET_CSRF = 'CUAN_IMPORT_SRV/$metadata'
ODATA_LOGOFF_URL = ODATA_TENANT_URL + '/sap/public/bc/icf/logoff'
ODATA_POST_IMPORT_HEADERS = 'CUAN_IMPORT_SRV/ImportHeaders'
ODATA_POST_CAMPANAS_CONSULTORA_BATCH = 'YY1_CAMPANAS_CONSULTORA_CDS/$batch'
ODATA_POST_CAMPANAS_CONSULTORA = 'YY1_CAMPANAS_CONSULTORA_CDS/YY1_CAMPANAS_CONSULTORA'
ODATA_SESSION_MAX_TTL = 30 # Minutes
ODATA_IDLE_TIME = 2 # Seconds
ODATA_CONTACT_BATCH_SIZE = 5000
ODATA_CAMPANAS_CONSULTORA_BATCH_SIZE = 100

# Constants
ODATA_CONTACT = 'Contacts'
ODATA_INTERACTION = 'Interactions'
ODATA_CAMPANA_CONSULTORA = 'CampanaConsultora'
