# -*- coding: utf-8 -*-
# INPUT SETTINGS
SOURCE_FOLDER = 'C:\IDATHA\PYXIS\BELCORP - Hybris Marketing\Datos'
SOURCE_FILE = 'Contacto_DC_20180306.csv'
OUTPUT_FOLDER = 'C:\IDATHA\PYXIS\BELCORP - Hybris Marketing\Datos\Transformados\Desarollo'
SOURCE_ENCODING = 'utf8'
SOURCE_DELIMITER = ','

# OUTPUT SETTINGS
MODE = 'PRODUCTIVE'
# MODE = 'TEST'
TEST_MAIL = 'brunoo.gonzalez+{}@gmail.com'
BATCH_SIZE = 4500
PREFIX_CONTACT = 'CONTACTS'
PREFIX_APP_INSTALLED = 'APP_TOKEN_INTERACTIONS'
PREFIX_CAMPANA_CONSULTORA = 'CBO_CAMPANAS_CONSULTORA'
OUTPUT_FILE_TYPES = [PREFIX_CONTACT, PREFIX_APP_INSTALLED, PREFIX_CAMPANA_CONSULTORA]

# PHONE VALIDATION
PHONE_REGEX = '^\+\d{11}$'

# EMAIL VALIDATION
LOCAL_PART_REGEX = '^[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&*+-/=?^_`''{|}~\.]+$'
